<a href="https://colab.research.google.com/github/Parkjaeseong33/python_programming/blob/main/11%EC%A3%BC_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#11주차 HW 박재성
import numpy as np


In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])

In [4]:
print(a[0])

1


In [5]:
import numpy as np
a = np.array([1, 2, 3])

In [6]:
np.zeros(2)

array([0., 0.])

In [7]:
np.ones(2)

array([1., 1.])

In [9]:
np.empty(2)

array([1., 1.])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [11]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [12]:
np.linspace(0, 10, num=5)


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [17]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [20]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [21]:
array_example.ndim

3

In [23]:
array_example.size

24

In [24]:
array_example.shape

(3, 2, 4)

In [25]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [26]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [27]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [29]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [30]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [31]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [34]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [35]:
data = np.array([1, 2, 3])

data[1]

2

In [36]:
data[0:2]

array([1, 2])

In [37]:
data[1:]

array([2, 3])

In [38]:
data[-2:]

array([2, 3])

In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])

[1 2 3 4]


In [40]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [41]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [42]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [43]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [44]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [45]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [47]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [48]:
print(a[b])

[1 2 3 4]


In [49]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [50]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr1 = a[3:8]
arr1


array([4, 5, 6, 7, 8])

In [52]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [53]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [54]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [55]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [56]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [57]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [59]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [60]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [61]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
b2 = a.copy()

In [63]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [64]:
data - ones

array([0, 1])

In [65]:
data * data

array([1, 4])

In [66]:
data / data

array([1., 1.])

In [67]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [68]:
b = np.array([[1, 1], [2, 2]])

In [69]:
b.sum(axis=0)

array([3, 3])

In [70]:
b.sum(axis=1)

array([2, 4])

In [71]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [72]:
data.max()

2.0

In [73]:
data.min()

1.0

In [74]:
data.sum()

3.0

In [75]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [76]:
a.sum()

4.8595784

In [77]:
a.min()

0.05093587

In [78]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [79]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [80]:
data[0, 1]

2

In [81]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [82]:
data[0:2, 0]

array([1, 3])

In [83]:
data.max()

6

In [84]:
data.min()

1

In [85]:
data.sum()

21

In [86]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [87]:
data.max(axis=0)

array([5, 6])

In [88]:
data.max(axis=1)

array([2, 5, 6])

In [89]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [90]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [91]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
np.ones(3)

array([1., 1., 1.])

In [93]:
np.zeros(3)

array([0., 0., 0.])

In [94]:
rng = np.random.default_rng()  
rng.random(3) 

array([0.96999426, 0.05551029, 0.04208211])

In [95]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [96]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [97]:
rng.random((3, 2)) 

array([[0.59453854, 0.32705593],
       [0.5614334 , 0.63477224],
       [0.57767282, 0.51947962]])

In [98]:
rng.integers(5, size=(2, 4)) 

array([[3, 1, 4, 0],
       [0, 1, 0, 0]])

In [100]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [101]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [102]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [103]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [104]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [105]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [106]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [108]:
print(indices)

[0 1 2]


In [109]:
print(occurrence_count)

[2 1 1]


In [110]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [113]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [114]:
arr.transpose()


array([[0, 3],
       [1, 4],
       [2, 5]])

In [115]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [116]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [117]:
reversed_arr = np.flip(arr)

In [118]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [119]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [120]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [121]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)


[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [122]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [123]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [124]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [125]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [126]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [127]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [128]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [129]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [130]:
print(a2)  # New array

[98  2  3  4  5  6  7  8  9 10 11 12]
